version: "3.9"

services:
  postgres:
    container_name: postgres
    image: dnaby/postgres:latest
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dnaby@ept.sn
      PGADMIN_DEFAULT_PASSWORD: passer123
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8888:80"
    depends_on:
      - postgres

  django: 
    build: ./devopsDjangoApp
    image: dev-ops-course-project-django:latest
    container_name: django
    environment:
      DB_NAME: db
      DB_USER: root
      DB_PASSWORD: passer123
      DB_HOST: postgres
      DB_PORT: 5432
    command: sh -c
      "sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./devopsDjangoApp/:/app/
    ports:
      - "8000:8000"
    depends_on:
      - postgres