apiVersion: v1
kind: Secret
metadata:
  name: database-info
type: Opaque
data:
  DB_NAME: ZGI=
  DB_USER: cm9vdA==
  DB_PASSWORD: cGFzc2VyMTIz
  DB_HOST: cG9zdGdyZXMtY2x1c3Rlci1pcC1zZXJ2aWNl
  DB_PORT: NTQzMg==